CREATE DATABASE IF NOT EXISTS ecommerce_interview;
USE ecommerce_interview;
CREATE TABLE customers (
    customer_id INT PRIMARY KEY,
    customer_name VARCHAR(100) NOT NULL,
    city VARCHAR(50),
    country VARCHAR(50),
    signup_date DATE
);
CREATE TABLE products (
    product_id INT PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL,
    category VARCHAR(50),
    price DECIMAL(10,2) NOT NULL,
    stock INT DEFAULT 0
);
CREATE TABLE orders (
    order_id INT PRIMARY KEY,
    customer_id INT NOT NULL,
    order_date DATE NOT NULL,
    status VARCHAR(30),
    payment_method VARCHAR(30),
    FOREIGN KEY (customer_id)
    REFERENCES customers(customer_id)
);
CREATE TABLE order_items (
    order_item_id INT PRIMARY KEY,
    order_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL,
    unit_price DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (order_id)
    REFERENCES orders(order_id),
    FOREIGN KEY (product_id)
    REFERENCES products(product_id)
);

-- PART-1
-- Q1.Show all customers from Bengaluru.
select *
 from customers
 where city="Bengaluru";
 
 -- Q2.Show customers who signed up after ‘2025-01-01’
 select * 
 from customers
 where signup_date > "2025-01-01";
 
 -- Q3.Find customers from Mumbai and Hyderabad. 
 select *
 from customers
 where city in ("Mumbai","Hyderabad");
 
 -- Q4.Show products belonging to the Electronics category.
 select *
 from products
 where category="Electronics";
 
 --  Find products priced above 40000.
 select *
 from products
 where price>40000;
 
 -- Q5.Show products where stock is less than 20
 select *
 from products 
 where stock<20;
 
 -- Q6. Find products with stock between 50 and 100.
 select *
 from products
 where stock between 50 and 100;
 
 -- Q7. Show customers whose names start with ‘A’
 select * 
 from customers
 where customer_name like "A%";
 
 -- Q8. Find products whose names contain ‘Premium
 select *
 from products
 where product_name like "premium%";
 
 -- Q9. Show customers registered during the year 2025.
 select *
 from customers
 where signup_date like "2025%";
 
 -- Q10.  Find total revenue generated by each category.
 select category,sum(price) as total_revenue
 from products
 group by category
 order by total_revenue desc;
 
 -- PART-2
 
 -- Q11. Find total quantity sold for each product. 
 select p.product_name,sum(oi.quantity) as total_quantity
 from products as p
 join order_items as oi
 on p.product_id=oi.product_id
 group by p.product_name
 order by total_quantity desc;
 
 -- Q12. Find total quantity sold for each product
 select p.product_name,count(quantity) as total_quantity
 from products as p
 join order_items as oi
 on p.product_id=oi.product_id
 group by p.product_name
 order by total_quantity desc;
 
 -- Q13. Find total orders under each order status.
 select `status`,count(order_item_id) as total_orders
 from orders as o
 join order_items as oi
 on o.order_id=oi.order_id
 group by `status`
 order by total_orders desc;
 
 
 -- Q14. Find total revenue generated through each payment method.
 select o.payment_method,sum(oi.unit_price*oi.quantity) as total_revenue
 from orders as o
 join order_items as oi
 on o.order_id=oi.order_id
 group by o.payment_method
 order by total_revenue desc;
 
 -- Q15. Find average product price category-wise.
 select category,avg(price) as average
 from products
 group by category
 order by average desc;
 
 -- Q16.Find category-wise quantity sold
 select category,count(oi.quantity) as quantity_sold
 from products as p
 join order_items as oi
 on p.product_id=oi.product_id
 group by category
 order by quantity_sold desc;
 
 -- Q17. Find monthly order count
 select month(order_date) as `month`,count(o.order_id) as order_count
 from orders as o
 join order_items as oi
 on o.order_id=oi.order_id
 group by `month` 
 order by `month`;
 
 -- Q18. Find monthly revenue trend
 select month(o.order_date) as monthly,sum(oi.quantity*oi.unit_price) as total_revenue
 from orders as o
 join order_items as oi
 on o.order_id=oi.order_id
 group by monthly
 order by monthly;
 
 -- Q19. Find the most commonly used payment method
 select payment_method,count(*) as usage_method
 from orders as o
 group by payment_method
 order by usage_method desc;
 
 -- Q20. Find the highest revenue-generating category.
 select category,sum(oi.quantity*oi.unit_price) as revenue
 from products as p
 join order_items as oi
 on p.product_id=oi.product_id
 group by category
 order by revenue desc
 limit 1;
 
 
 -- Q21. Find customers who placed more than 5 orders
 select c.customer_id,c.customer_name,count(o.order_id) as orders
 from customers as c
 join orders as o
 on c.customer_id=o.customer_id
 group by c.customer_id
 having orders > 5
 order by orders asc;
 
 -- Q22. Find top 5 customers based on total spending
 select c.customer_name,sum(oi.quantity*oi.unit_price) as spending
 from customers as c
 join orders as o
 on c.customer_id=o.customer_id
 join order_items as oi
 on o.order_id=oi.order_id
 group by c.customer_name
 order by spending desc
 limit 5;
 
 -- Q23. Find products sold more than 30 times
 select * from products;
 select * from order_items;
 select product_name,count(p.product_id) as times
 from products as p
 join order_items as oi
 on p.product_id=oi.product_id
 group by product_name
 having times > 30
 order by times desc;
 
 -- Q24. . Find categories generating revenue greater than 500000
 select category,sum(oi.quantity*oi.unit_price) as revenue
 from products as p
 join order_items as oi
 on p.product_id=oi.product_id
 group by category
 having revenue > 500000
 order by revenue desc;
 
 -- Q25. Find cities having more than 10 customers
 select city,count(c.customer_id) as customers
 from customers as c
 group by city
 having customers>10
 order by customers;
 
 -- Q26. Find the top 5 highest-selling products.
 select product_name,sum(oi.quantity) as selling
 from products as p
 join order_items as oi
 on p.product_id=oi.product_id
 group by product_name
 order by selling desc
 limit 5;
 select * from products;
 select * from order_items;
 -- Q27. Find the top 3 most profitable products.
 select p.product_name,SUM(oi.quantity * oi.unit_price) AS profit
 from products as p
 join order_items as oi
 on p.product_id=oi.product_id
 group by product_name
 order by profit desc
 limit 3;
 
 -- Q28. Find customers whose spending is above average customer spending
 select c.customer_name,avg(oi.quantity * oi.unit_price) AS average
 from customers as c
 join orders as o
 on c.customer_id=o.customer_id
 join order_items as oi
 on o.order_id=oi.order_id
 group by c.customer_name
 order by average desc;
 
 -- Q29.  Find products contributing more than 10% of company revenue.
 select product_name,sum(oi.quantity*oi.unit_price) as revenue
 from products as p
 join order_items as oi
 on p.product_id=oi.product_id
 group by product_name
 having revenue >
 (
   SELECT SUM(oi.quantity * oi.unit_price) *0.10
    FROM order_items as oi
);
SELECT SUM(oi.quantity * oi.unit_price) *"0.10"
FROM order_items as oi;

-- Q30. Find the city generating the highest revenue
 select c.city,sum(oi.quantity * oi.unit_price) AS revenue
 from customers as c
 join orders as o
 on c.customer_id=o.customer_id
 join order_items as oi
 on o.order_id=oi.order_id
 group by c.city
 order by revenue desc
 limit 1;
 
 
 
 
 
 
 
 
